# Contains the app configuration for the authentication server
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldtteam-authentication-server.fullname" . }}-environment
  labels:
    {{- include "ldtteam-authentication-server.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.environment | nindent 2 }}