version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-ldtteam-auth-db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 5672:5672
      - 15672:15672
      

volumes:
  postgres-ldtteam-auth-db: